tasks:
  - name: Utils
    before: sudo apt-get install tree

  - name: Install aws cli
    before: sh ./bin/aws-cli.sh

  - name: Install terraform cli
    before: sh ./bin/terraform.sh

  - name: Install aws cdk
    before: npm install -g aws-cdk

  - name: Install pulumi
    before: sh ./bin/pulumi.sh
    
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    
