tasks:
  - name: Utils
    before: |
      sudo apt-get install tree
  - name: Install aws cli
    before: |
      cd /workspace 
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      cd $THEIA_WORKSPACE_ROOT
  - name: Install terraform cli
    before: sh ./bin/terraform.sh
  - name: Install aws cdk
    before: |
      npm install -g aws-cdk
  - name: Install pulumi
    before: |
      curl -fsSL https://get.pulumi.com | sh
      export PATH=$HOME/.pulumi/bin:$PATH
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    
